### ISSUE TITLE
[FEAT] Allow Toolbar Plugins to Execute a Local Command

### ISSUE THREAD

**Issue by starfishpatkhoo** [eythaann/Seelen-UI#830]
Allow Toolbar Plugins to execute a local command, in the same way as a remote request. We would expect the return result to be text and we can put that in the toolbar, the same was as we do `remoteData`. Here is a possible definition in the plugin YAML:

```
  localData:
    mydata:
      updateIntervalSeconds: 600
      cmd: cmd.exe /c "c:\some path\checker.bat"
```

Lots of possible uses for this I feel, from checking status of all sorts of things, to integrating with other CLI-based softwares/systems etc etc...
